import { useMemo, useState } from 'react'
import { Activity, ArrowDownRight, ArrowUpRight, Coins, Gauge, RefreshCw, Search, TrendingUp } from 'lucide-react'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { useI18n } from '../i18n'

type RangeKey = '24h' | '7d' | '30d'
type RankingTab = 'agent' | 'model'
type TraceStatus = 'success' | 'failed'
interface Trace { id: string; agent: string; node: string; model: string; tokens: string; latency: string; status: TraceStatus; time: string }

const trend = [
  { time: '00:00', prompt: 320, completion: 180 }, { time: '04:00', prompt: 280, completion: 155 },
  { time: '08:00', prompt: 760, completion: 390 }, { time: '12:00', prompt: 920, completion: 470 },
  { time: '16:00', prompt: 1080, completion: 550 }, { time: '20:00', prompt: 1260, completion: 680 },
]
const agents = [{ name: 'Code Reviewer', value: 48 }, { name: 'Developer', value: 31 }, { name: 'Data Analyst', value: 14 }, { name: 'Researcher', value: 7 }]
const models = [{ name: 'Claude 3.5', value: 42 }, { name: 'GPT-4o', value: 31 }, { name: 'DeepSeek-V3', value: 18 }, { name: 'Qwen-Max', value: 9 }]
const traces: Trace[] = [
  { id: 'tr_8f2a91c', agent: 'Code Reviewer', node: '中转站-主通道', model: 'Claude 3.5', tokens: '56.6k', latency: '620ms', status: 'success', time: '刚刚' },
  { id: 'tr_31c07bd', agent: 'Developer', node: '备用中转站', model: 'GPT-4o', tokens: '38.9k', latency: '488ms', status: 'success', time: '2 分钟前' },
  { id: 'tr_4a0e112', agent: 'Code Reviewer', node: '中转站-主通道', model: 'DeepSeek-V3', tokens: '33.5k', latency: '1.24s', status: 'success', time: '8 分钟前' },
  { id: 'tr_9dd81ea', agent: 'Developer', node: '官方直连', model: 'Claude 3.5', tokens: '74.0k', latency: '2.05s', status: 'failed', time: '12 分钟前' },
  { id: 'tr_6bc30fa', agent: 'Researcher', node: '中转站-主通道', model: 'GPT-4o', tokens: '21.8k', latency: '712ms', status: 'success', time: '18 分钟前' },
]

function MetricCard({ icon, label, value, detail, change, down = false }: { icon: React.ReactNode; label: string; value: string; detail: string; change: string; down?: boolean }) {
  return <article className="rounded-lg border border-border bg-card p-5 shadow-sm">
    <div className="flex items-center gap-2 text-xs font-medium uppercase tracking-wide text-muted-foreground"><span className="grid h-7 w-7 place-items-center rounded-md border border-border bg-muted text-foreground">{icon}</span>{label}</div>
    <div className="mt-4 text-3xl font-bold tracking-tight text-foreground">{value}</div>
    <div className="mt-3 flex items-center gap-2 text-xs text-muted-foreground"><span className={`inline-flex items-center gap-0.5 font-medium ${down ? 'text-emerald-600 dark:text-emerald-400' : 'text-foreground'}`}>{down ? <ArrowDownRight size={13} /> : <ArrowUpRight size={13} />}{change}</span><span>{detail}</span></div>
  </article>
}

export default function Metrics() {
  const { t } = useI18n()
  const [range, setRange] = useState<RangeKey>('24h')
  const [tab, setTab] = useState<RankingTab>('agent')
  const [query, setQuery] = useState('')
  const [refreshing, setRefreshing] = useState(false)
  const filtered = useMemo(() => traces.filter((trace) => `${trace.id} ${trace.agent} ${trace.model} ${trace.node}`.toLowerCase().includes(query.toLowerCase())), [query])
  const ranking = tab === 'agent' ? agents : models
  const refresh = () => { setRefreshing(true); window.setTimeout(() => setRefreshing(false), 700) }
  return <main className="w-full min-h-screen px-6 py-6 2xl:px-10">
    <header className="mb-6 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="mb-2 text-xs font-medium uppercase tracking-wider text-muted-foreground">{t('common.controlPlane')} / {t('nav.metrics')}</p><h1 className="text-2xl font-bold tracking-tight text-foreground">{t('metrics.title')}</h1><p className="mt-1 text-sm text-muted-foreground">{t('metrics.subtitle')}</p></div><div className="flex items-center gap-2"><div className="flex rounded-md border border-border bg-card p-1">{(['24h', '7d', '30d'] as RangeKey[]).map((key) => <button type="button" key={key} onClick={() => setRange(key)} className={`rounded px-3 py-1.5 text-xs transition-colors ${range === key ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:bg-muted'}`}>{t(`metrics.range${key}`)}</button>)}</div><button type="button" onClick={refresh} className="grid h-9 w-9 place-items-center rounded-md border border-border bg-card text-muted-foreground hover:bg-muted" aria-label={t('metrics.refresh')}><RefreshCw size={15} className={refreshing ? 'animate-spin' : ''} /></button></div></header>
    <section className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4"><MetricCard icon={<TrendingUp size={15} />} label={t('metrics.totalTokens')} value="1.08B" detail={t('metrics.vsPrevious')} change="12.4%" /><MetricCard icon={<Activity size={15} />} label={t('metrics.sessions')} value="1,269" detail={t('metrics.activePeriod')} change="24h" /><MetricCard icon={<Coins size={15} />} label={t('metrics.estimatedCost')} value="$4.2k" detail={t('metrics.modelPricing')} change="3.1%" down /><MetricCard icon={<Gauge size={15} />} label={t('metrics.p95Health')} value="480ms" detail={t('metrics.successRate')} change="99.9%" /></section>
    <section className="mt-4 grid grid-cols-1 gap-4 lg:grid-cols-12"><div className="rounded-lg border border-border bg-card p-5 lg:col-span-8"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-sm font-semibold text-foreground">{t('metrics.tokenTrend')}</h2><p className="mt-1 text-xs text-muted-foreground">{t(`metrics.range${range}`)}</p></div><div className="flex gap-4 text-xs text-muted-foreground"><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-foreground" />{t('metrics.prompt')}</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-muted-foreground" />{t('metrics.completion')}</span></div></div><div className="h-[280px] w-full"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend}><CartesianGrid stroke="hsl(var(--border))" strokeDasharray="3 3" vertical={false} /><XAxis dataKey="time" tick={{ fill: 'hsl(var(--muted-foreground))', fontSize: 10 }} axisLine={false} tickLine={false} /><YAxis tick={{ fill: 'hsl(var(--muted-foreground))', fontSize: 10 }} axisLine={false} tickLine={false} /><Tooltip contentStyle={{ background: 'hsl(var(--card))', border: '1px solid hsl(var(--border))', borderRadius: 8, fontSize: 12 }} /><Area type="monotone" dataKey="prompt" stackId="tokens" stroke="hsl(var(--foreground))" fill="hsl(var(--foreground))" fillOpacity={0.16} /><Area type="monotone" dataKey="completion" stackId="tokens" stroke="hsl(var(--muted-foreground))" fill="hsl(var(--muted-foreground))" fillOpacity={0.18} /></AreaChart></ResponsiveContainer></div></div>
      <div className="rounded-lg border border-border bg-card p-5 lg:col-span-4"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold text-foreground">{t('metrics.ranking')}</h2><Activity size={16} className="text-muted-foreground" /></div><div className="mt-4 flex border-b border-border">{(['agent', 'model'] as RankingTab[]).map((key) => <button type="button" key={key} onClick={() => setTab(key)} className={`border-b-2 px-3 pb-2 text-xs font-medium ${tab === key ? 'border-foreground text-foreground' : 'border-transparent text-muted-foreground'}`}>{t(`metrics.${key}Rank`)}</button>)}</div><div className="mt-4 space-y-4">{ranking.map((item, index) => <div key={item.name}><div className="mb-1 flex justify-between text-xs"><span className="text-foreground">{index + 1}. {item.name}</span><span className="font-mono text-muted-foreground">{item.value}%</span></div><div className="h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-foreground" style={{ width: `${item.value}%` }} /></div></div>)}</div></div></section>
    <section className="mt-4 rounded-lg border border-border bg-card"><div className="flex flex-col gap-3 border-b border-border p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-sm font-semibold text-foreground">{t('metrics.recentTraces')}</h2><p className="mt-1 text-xs text-muted-foreground">{t('metrics.traceSubtitle')}</p></div><div className="relative"><Search size={14} className="absolute left-3 top-2.5 text-muted-foreground" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t('metrics.filter')} className="h-9 w-full rounded-md border border-border bg-background pl-9 pr-3 text-xs outline-none focus:ring-1 focus:ring-ring sm:w-56" /></div></div><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-muted/50 text-muted-foreground"><tr>{[t('metrics.time'), 'Trace ID', t('metrics.agent'), t('metrics.node'), t('metrics.model'), t('metrics.total'), t('metrics.latency'), t('metrics.status')].map((head) => <th key={head} className="whitespace-nowrap px-5 py-3 font-medium">{head}</th>)}</tr></thead><tbody>{filtered.map((trace) => <tr key={trace.id} className="border-t border-border hover:bg-muted/50"><td className="whitespace-nowrap px-5 py-3 text-muted-foreground">{trace.time}</td><td className="whitespace-nowrap px-5 py-3 font-mono text-[11px]">{trace.id}</td><td className="whitespace-nowrap px-5 py-3">{trace.agent}</td><td className="whitespace-nowrap px-5 py-3 text-muted-foreground">{trace.node}</td><td className="whitespace-nowrap px-5 py-3">{trace.model}</td><td className="whitespace-nowrap px-5 py-3 font-mono">{trace.tokens}</td><td className="whitespace-nowrap px-5 py-3 font-mono text-muted-foreground">{trace.latency}</td><td className="px-5 py-3"><span className="inline-flex items-center gap-1.5 rounded-full border border-border px-2 py-0.5"><i className={`h-1.5 w-1.5 rounded-full ${trace.status === 'success' ? 'bg-emerald-500' : 'bg-rose-500'}`} />{t(`metrics.${trace.status}`)}</span></td></tr>)}</tbody></table></div></section>
  </main>
}
