import { useState, useEffect } from 'react'
import { ThemeProvider, useTheme } from 'next-themes'
import { Activity, ArrowUpRight, BarChart3, Bot, ChevronRight, ChevronsLeft, ChevronsRight, Cpu, GitFork, Languages, LayoutDashboard, HeartPulse, Menu, Moon, Plus, Server, Sun } from 'lucide-react'
import Metrics from './pages/Metrics'
import Agents from './pages/Agents'
import Routes from './pages/Routes'
import { LanguageProvider, useI18n } from './i18n'
import './App.css'

type NavId = 'overview' | 'agents' | 'routes' | 'metrics'
const navItems = [
  { id: 'overview' as NavId, icon: LayoutDashboard }, { id: 'agents' as NavId, icon: Bot }, { id: 'routes' as NavId, icon: GitFork }, { id: 'metrics' as NavId, icon: BarChart3 },
]
function ThemeToggle() { const { resolvedTheme, setTheme } = useTheme(); const dark = resolvedTheme === 'dark'; return <button className="theme-toggle" onClick={() => setTheme(dark ? 'light' : 'dark')} type="button" aria-label={dark ? 'Light mode' : 'Dark mode'}>{dark ? <Sun size={15} /> : <Moon size={15} />}</button> }
function LanguageToggle() { const { language, setLanguage } = useI18n(); return <div className="language-toggle" role="group" aria-label="Language"><Languages size={13} className="lang-glyph" /><button className={language === 'zh-CN' ? 'selected' : ''} onClick={() => setLanguage('zh-CN')} type="button" aria-pressed={language === 'zh-CN'}>中</button><button className={language === 'en' ? 'selected' : ''} onClick={() => setLanguage('en')} type="button" aria-pressed={language === 'en'}>EN</button></div> }
function Sidebar({ active, onNavigate, collapsed, onToggleCollapsed, mobileOpen }: { active: NavId; onNavigate: (id: NavId) => void; collapsed: boolean; onToggleCollapsed: () => void; mobileOpen: boolean }) { const { t } = useI18n(); return <aside className={`sidebar${collapsed ? ' collapsed' : ''}${mobileOpen ? ' open' : ''}`}><div className="sidebar-head"><div className="brand">AGENT<span>GATEWAY</span></div><button className="collapse-btn" onClick={onToggleCollapsed} type="button" aria-label="Toggle sidebar">{collapsed ? <ChevronsRight size={16} /> : <ChevronsLeft size={16} />}</button></div><div className="workspace-chip"><span className="online-dot" />{t('common.workspace')}<ChevronRight size={13} /></div><nav className="nav-list"><div className="nav-kicker">{t('nav.workspace')}</div>{navItems.map(({ id, icon: Icon }) => <button className={`nav-item ${active === id ? 'active' : ''}`} key={id} onClick={() => onNavigate(id)} type="button" title={t(`nav.${id}`)}><Icon size={17} strokeWidth={1.8} /><span>{t(`nav.${id}`)}</span></button>)}</nav><div className="sidebar-bottom"><div className="control-row"><LanguageToggle /><ThemeToggle /></div><div className="sidebar-footer"><span>v0.8.4</span><span className="footer-status"><span className="online-dot" />{t('common.operational')}</span></div></div></aside> }
function HeartPulseIcon() { return <HeartPulse size={16} className="muted-icon" /> }
function MetricCard({ icon: Icon, label, value, link, tone, onClick }: { icon: typeof Server; label: string; value: string; link: string; tone: string; onClick: () => void }) { return <article className="metric-card"><div className="metric-top"><span className={`metric-icon ${tone}`}><Icon size={16} /></span><span>{label}</span><ArrowUpRight size={15} className="metric-arrow" /></div><strong>{value}</strong><button className="metric-link" onClick={onClick} type="button">{link}<ArrowUpRight size={14} /></button></article> }
function Overview({ onNavigate }: { onNavigate: (id: NavId) => void }) { const { t } = useI18n(); return <div className="overview"><div className="page-head"><div><div className="breadcrumb"><span>{t('common.controlPlane')}</span><ChevronRight size={13} /><span>{t('nav.overview')}</span></div><h1>{t('overview.greeting')}</h1><p>{t('overview.subtitle')}</p></div><span className="sync-label"><span className="online-dot" />{t('overview.synced')}</span></div><div className="metric-grid"><MetricCard icon={Bot} label={t('overview.activeAgents').toUpperCase()} value="3" link="Claude Code / Codex / 沙盒" tone="tone-violet" onClick={() => onNavigate('agents')} /><MetricCard icon={GitFork} label={t('overview.gatewayStatus').toUpperCase()} value="99.9%" link={t('overview.connectedRelays')} tone="tone-green" onClick={() => onNavigate('routes')} /><MetricCard icon={BarChart3} label={t('overview.todayTokens').toUpperCase()} value="2.45M" link={t('overview.vsYesterday')} tone="tone-blue" onClick={() => onNavigate('metrics')} /><MetricCard icon={Cpu} label={t('overview.todayCost').toUpperCase()} value="$6.82" link={t('overview.estimated')} tone="tone-orange" onClick={() => onNavigate('metrics')} /></div><div className="content-grid overview-live-grid"><section className="panel task-flow-panel"><div className="panel-heading"><div><span className="eyebrow">AGENT RUNTIME</span><h2>{t('overview.taskFlow')}</h2></div><Activity size={16} className="muted-icon" /></div><div className="flow-list"><div><span className="flow-status running" /><span>Claude Code</span><b>Refactoring auth middleware</b><em>running</em></div><div><span className="flow-status running" /><span>Codex Runner</span><b>Review pull request #184</b><em>running</em></div><div><span className="flow-status idle" /><span>Python Sandbox</span><b>Idle · awaiting assignment</b><em>idle</em></div><div><span className="flow-status failed" /><span>Docker Agent</span><b>Dependency audit</b><em>failed</em></div></div></section><section className="panel latency-panel"><div className="panel-heading"><div><span className="eyebrow">LLM GATEWAY</span><h2>{t('overview.liveLatency')}</h2></div><HeartPulseIcon /></div><div className="latency-list"><div><span className="online-dot" /><div><b>中转站-主通道</b><small>https://api.b.ai/v1</small></div><strong>180ms</strong></div><div><span className="online-dot" /><div><b>备用中转站</b><small>https://ai.akile.ai/v1</small></div><strong>246ms</strong></div><div><span className="offline-dot" /><div><b>官方直连</b><small>standby / emergency</small></div><strong>382ms</strong></div></div></section></div><div className="quick-entry-row"><button onClick={() => onNavigate('agents')} type="button"><Plus size={16} />{t('overview.launchAgent')}</button><button onClick={() => onNavigate('routes')} type="button"><Plus size={16} />{t('overview.addRelay')}</button><button onClick={() => onNavigate('metrics')} type="button"><ArrowUpRight size={16} />{t('overview.viewBilling')}</button></div></div> }
function AppShell() { const [active, setActive] = useState<NavId>('overview'); const [collapsed, setCollapsed] = useState<boolean>(() => localStorage.getItem('agent-sidebar-collapsed') === '1'); const [mobileOpen, setMobileOpen] = useState(false); useEffect(() => { localStorage.setItem('agent-sidebar-collapsed', collapsed ? '1' : '0') }, [collapsed]); const navigate = (id: NavId) => { setActive(id); setMobileOpen(false) }; const toggleCollapsed = () => setCollapsed(c => !c); return <div className="app-shell"><Sidebar active={active} onNavigate={navigate} collapsed={collapsed} onToggleCollapsed={toggleCollapsed} mobileOpen={mobileOpen} />{mobileOpen && <div className="sidebar-overlay" onClick={() => setMobileOpen(false)} />}<main className="main-content"><button className="menu-trigger" onClick={() => setMobileOpen(true)} type="button" aria-label="Open menu"><Menu size={18} /></button>{active === 'overview' ? <Overview onNavigate={navigate} /> : active === 'metrics' ? <Metrics /> : active === 'agents' ? <Agents /> : <Routes />}</main></div> }
export default function App() { return <LanguageProvider><ThemeProvider attribute="class" defaultTheme="dark" enableSystem={false}><AppShell /></ThemeProvider></LanguageProvider> }
